apiVersion: v1
kind: ServiceAccount
metadata:
  name: superadmin
  namespace: vkdr-expose

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superadmin-binding
subjects:
  - kind: ServiceAccount
    name: superadmin
    namespace: vkdr-expose
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: superadmin-token
  namespace: vkdr-expose
  annotations:
    kubernetes.io/service-account.name: superadmin
type: kubernetes.io/service-account-token