apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "${user_name}-pg-dyn-secret"
  namespace: vkdr
spec:
  path: "/database/static-creds/${user_name}"
  method: "GET"
  provider:
    server: "http://vault:8200"
    auth:
      tokenSecretRef:
        name: "vault-keys"
        key: "root-token"

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${user_name}-pg-ext-secret"
  namespace: "vkdr"
spec:
  refreshInterval: "1h"
  target:
    name: "${user_name}-pg-secret"
    template:
      data:
        dbname: "${db_name}"
        password: "{{ .password }}"
        user: "${user_name}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: "${user_name}-pg-dyn-secret"
