apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    backstage.io/kubernetes-id: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    backstage.io/kubernetes-id: petclinic
  name: petclinic
spec:
  ingressClassName: kong
  rules:
  - host: petclinic.localhost
    http:
      paths:
      - backend:
          service:
            name: petclinic
            port:
              number: 80
        path: /
        pathType: Prefix
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    backstage.io/kubernetes-id: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
        backstage.io/kubernetes-id: petclinic
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: app
        image: ghcr.io/pavolloffay/spring-petclinic:latest