
kind: Service
apiVersion: v1
metadata:
  name: cep
  annotations:
    konghq.com/path: "/ws"
spec:
  type: ExternalName
  externalName: viacep.com.br
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cep-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
    konghq.com/protocols: "http"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /cep
            pathType: Prefix
            backend:
              service:
                name: cep
                port:
                  number: 80
