apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-devportal-read-only
  namespace: vkdr
rules:
  - apiGroups:
      - '*'
    resources:
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - horizontalpodautoscalers
      - ingressclasses
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - replicasets
      - services
      - statefulsets
      - resourcequotas
      - resources
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
    - core.k8sgpt.ai
    resources:
    - results
    - result
    verbs:
    - get
    - list