apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-devportal-read-only
  namespace: vkdr
roleRef:
  kind: ClusterRole
  name: platform-devportal-read-only
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: platform-devportal
    namespace: vkdr