package codes.vee.vkdr.cmd.completions;

import picocli.AutoComplete;
import picocli.CommandLine.Model.CommandSpec;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

/**
 * All logic behind `vkdr completions`.
 *
 * This lives in Java rather than a formula because the script content can only come from the
 * picocli CommandSpec, and because `~/.vkdr/formulas/` does not exist until `vkdr init` runs -
 * completions must work on a fresh machine.
 */
public final class CompletionsSupport {

    private CompletionsSupport() {
    }

    public static final String BEGIN = "# >>> vkdr completions >>>";
    public static final String END = "# <<< vkdr completions <<<";

    private static final String SCRIPT_NAME = "vkdr.bash";
    private static final String ZSH_WRAPPER_NAME = "_vkdr";

    /** Outcome of a file or rc-block operation. */
    public enum Change {
        ADDED, UPDATED, UNCHANGED, REMOVED, ABSENT
    }

    // ------------------------------------------------------------------
    // Generation
    // ------------------------------------------------------------------

    /**
     * Renders the completion script for the ROOT command, whatever our depth in the tree.
     * `spec.root()` walks up to `vkdr`, so we never need the root CommandLine stashed anywhere.
     */
    public static String generate(CommandSpec spec) {
        CommandSpec root = spec.root();
        return stripZshGlobalSideEffects(AutoComplete.bash(root.name(), root.commandLine()));
    }

    /**
     * picocli's generated header runs two statements that permanently alter the user's zsh:
     * `setopt COMPLETE_ALIASES` (changes completion for every alias in the shell) and
     * `alias compopt=complete` (a global alias nobody asked for). picocli's own call sites
     * already guard with `type compopt &>/dev/null &&`, so dropping both is safe.
     * Matching is done on the trimmed line so a change in picocli's indentation still works.
     */
    static String stripZshGlobalSideEffects(String script) {
        StringBuilder out = new StringBuilder(script.length());
        for (String line : script.split("\n", -1)) {
            String trimmed = line.trim();
            if (trimmed.equals("setopt COMPLETE_ALIASES") || trimmed.equals("alias compopt=complete")) {
                continue;
            }
            if (out.length() > 0) {
                out.append('\n');
            }
            out.append(line);
        }
        return out.toString();
    }

    /**
     * A lazy #compdef wrapper for zsh. Dropped into a directory already on $fpath, zsh loads it
     * only on the first TAB after `vkdr`, so shell startup cost is zero.
     */
    public static String zshWrapper(Path script) {
        return "#compdef vkdr\n"
                + "# vkdr zsh completion - generated by 'vkdr completions install'.\n"
                + "# Refreshed automatically by 'vkdr init'.\n"
                + "_vkdr() {\n"
                + "  local script=\"${VKDR_COMPLETION_SCRIPT:-" + homeVarPath(script) + "}\"\n"
                + "  [[ -r $script ]] || return 1\n"
                + "  (( $+functions[_bash_complete] )) || { autoload -U +X bashcompinit && bashcompinit; }\n"
                + "  (( $+functions[_complete_vkdr] )) || source $script\n"
                + "  _bash_complete -o default -F _complete_vkdr\n"
                + "}\n"
                + "_vkdr \"$@\"\n";
    }

    // ------------------------------------------------------------------
    // Paths
    // ------------------------------------------------------------------

    public static Path completionsDir() {
        String override = System.getenv("VKDR_COMPLETIONS_DIR");
        if (override != null && !override.isEmpty()) {
            return Paths.get(override);
        }
        return Paths.get(userHome(), ".vkdr", "completions");
    }

    public static Path scriptPath() {
        return completionsDir().resolve(SCRIPT_NAME);
    }

    public static Path zshWrapperPath() {
        return completionsDir().resolve(ZSH_WRAPPER_NAME);
    }

    static String userHome() {
        return System.getProperty("user.home");
    }

    /** Renders an absolute path under $HOME as "$HOME/..." so the rc block survives a home move. */
    static String homeVarPath(Path path) {
        String home = userHome();
        String s = path.toString();
        return s.startsWith(home + "/") ? "$HOME" + s.substring(home.length()) : s;
    }

    static String expandHome(String path) {
        if (path.equals("~")) {
            return userHome();
        }
        return path.startsWith("~/") ? userHome() + path.substring(1) : path;
    }

    // ------------------------------------------------------------------
    // Detection
    // ------------------------------------------------------------------

    /** Explicit flag wins, then $SHELL, then bash. */
    public static Shell detectShell(Shell explicit) {
        if (explicit != null) {
            return explicit;
        }
        String sh = System.getenv("SHELL");
        if (sh != null && !sh.isEmpty()) {
            String base = sh.substring(sh.lastIndexOf('/') + 1).toLowerCase(Locale.ROOT);
            if (base.contains("zsh")) {
                return Shell.zsh;
            }
            if (base.contains("bash")) {
                return Shell.bash;
            }
        }
        return Shell.bash;
    }

    /**
     * zsh always uses ${ZDOTDIR:-~}/.zshrc. bash prefers ~/.bashrc, falling back to
     * ~/.bash_profile only when .bashrc is absent - macOS Terminal runs login shells,
     * which read .bash_profile rather than .bashrc.
     */
    public static Path detectRcFile(Shell shell, String explicit) {
        if (explicit != null && !explicit.isEmpty()) {
            return Paths.get(expandHome(explicit));
        }
        if (shell == Shell.zsh) {
            String zdotdir = System.getenv("ZDOTDIR");
            String base = (zdotdir == null || zdotdir.isEmpty()) ? userHome() : zdotdir;
            return Paths.get(base, ".zshrc");
        }
        Path bashrc = Paths.get(userHome(), ".bashrc");
        if (Files.exists(bashrc)) {
            return bashrc;
        }
        for (String candidate : new String[]{".bash_profile", ".bash_login", ".profile"}) {
            Path p = Paths.get(userHome(), candidate);
            if (Files.exists(p)) {
                return p;
            }
        }
        return bashrc;
    }

    /**
     * A writable directory already on zsh's $fpath, so the wrapper needs no rc edit at all.
     * Returns null when none is available.
     */
    public static Path findZshFpathDir() {
        List<String> candidates = new ArrayList<>();
        addIfSet(candidates, System.getenv("ZSH_CUSTOM"), "completions");
        addIfSet(candidates, System.getenv("ZSH"), "completions");
        candidates.add("/opt/homebrew/share/zsh/site-functions");
        candidates.add("/usr/local/share/zsh/site-functions");
        for (String c : candidates) {
            Path p = Paths.get(c);
            if (Files.isDirectory(p) && Files.isWritable(p)) {
                return p;
            }
            // $ZSH_CUSTOM/completions is conventionally created on demand
            Path parent = p.getParent();
            if (parent != null && Files.isDirectory(parent) && Files.isWritable(parent)
                    && !Files.exists(p)) {
                return p;
            }
        }
        return null;
    }

    /**
     * bash-completion v2's per-command lazy-loading directory. Only used when bash-completion
     * v2 is actually present, otherwise the file would never be read.
     */
    public static Path findBashCompletionDir() {
        boolean v2Present = Files.isDirectory(Paths.get("/opt/homebrew/share/bash-completion/completions"))
                || Files.isDirectory(Paths.get("/usr/local/share/bash-completion/completions"))
                || Files.isDirectory(Paths.get("/usr/share/bash-completion/completions"));
        if (!v2Present) {
            return null;
        }
        String xdg = System.getenv("XDG_DATA_HOME");
        Path base = (xdg == null || xdg.isEmpty())
                ? Paths.get(userHome(), ".local", "share")
                : Paths.get(xdg);
        return base.resolve("bash-completion").resolve("completions");
    }

    /**
     * Where a no-rc ("lazy") install would place its payload for this shell, or null when the
     * shell has no directory we can use. Shared by install, status and uninstall so all three
     * agree on the location.
     */
    public static Path lazyTarget(Shell shell) {
        Path dir = (shell == Shell.zsh) ? findZshFpathDir() : findBashCompletionDir();
        return dir == null ? null : dir.resolve(shell == Shell.zsh ? ZSH_WRAPPER_NAME : "vkdr");
    }

    /** Payload for a no-rc install: the lazy zsh wrapper, or a one-line sourcing stub for bash. */
    public static String lazyPayload(Shell shell, Path script) {
        if (shell == Shell.zsh) {
            return zshWrapper(script);
        }
        String p = homeVarPath(script);
        return "# vkdr bash completion - generated by 'vkdr completions install'.\n"
                + "[ -f \"" + p + "\" ] && . \"" + p + "\"\n";
    }

    private static void addIfSet(List<String> out, String value, String child) {
        if (value != null && !value.isEmpty()) {
            out.add(Paths.get(value, child).toString());
        }
    }

    // ------------------------------------------------------------------
    // Writing
    // ------------------------------------------------------------------

    /** Idempotent: only touches the file when the content actually differs. */
    public static Change writeScript(String script, Path target) throws IOException {
        String content = script.endsWith("\n") ? script : script + "\n";
        boolean existed = Files.exists(target);
        if (existed && content.equals(Files.readString(target, StandardCharsets.UTF_8))) {
            return Change.UNCHANGED;
        }
        Files.createDirectories(target.getParent());
        writeAtomically(target, content);
        return existed ? Change.UPDATED : Change.ADDED;
    }

    public static List<String> rcBlock(Path script) {
        String p = homeVarPath(script);
        return Arrays.asList(
                BEGIN,
                "# Managed by 'vkdr completions install'. Do not edit inside this block.",
                "[ -f \"" + p + "\" ] && . \"" + p + "\"",
                END);
    }

    /**
     * Adds the block, or replaces an existing one IN PLACE so the user's chosen position in the
     * rc file is preserved. Never appends a second block.
     */
    public static Change upsertBlock(Path rcFile, List<String> block, boolean dryRun) throws IOException {
        List<String> lines = readLines(rcFile);
        int b = indexOfTrimmed(lines, BEGIN);
        int e = indexOfTrimmed(lines, END);
        requireBalanced(rcFile, b, e);

        List<String> out = new ArrayList<>(lines);
        Change change;
        if (b >= 0) {
            if (lines.subList(b, e + 1).equals(block)) {
                return Change.UNCHANGED;
            }
            out.subList(b, e + 1).clear();
            out.addAll(b, block);
            change = Change.UPDATED;
        } else {
            if (!out.isEmpty() && !out.get(out.size() - 1).trim().isEmpty()) {
                out.add("");
            }
            out.addAll(block);
            change = Change.ADDED;
        }
        if (!dryRun) {
            backup(rcFile);
            writeAtomically(rcFile, String.join("\n", out) + "\n");
        }
        return change;
    }

    /** Removes exactly the sentinel block, leaving everything else untouched. */
    public static Change removeBlock(Path rcFile, boolean dryRun) throws IOException {
        if (!Files.exists(rcFile)) {
            return Change.ABSENT;
        }
        List<String> lines = readLines(rcFile);
        int b = indexOfTrimmed(lines, BEGIN);
        int e = indexOfTrimmed(lines, END);
        requireBalanced(rcFile, b, e);
        if (b < 0) {
            return Change.ABSENT;
        }
        List<String> out = new ArrayList<>(lines);
        out.subList(b, e + 1).clear();
        // If the block sat at the end of the file behind a blank separator, that blank was ours
        // (see upsertBlock) - drop it so uninstall restores the file byte-for-byte.
        if (b == out.size() && b > 0 && out.get(b - 1).trim().isEmpty()) {
            out.remove(b - 1);
        }
        if (!dryRun) {
            backup(rcFile);
            writeAtomically(rcFile, out.isEmpty() ? "" : String.join("\n", out) + "\n");
        }
        return Change.REMOVED;
    }

    public static boolean hasBlock(Path rcFile) throws IOException {
        return Files.exists(rcFile) && indexOfTrimmed(readLines(rcFile), BEGIN) >= 0;
    }

    private static void requireBalanced(Path rcFile, int begin, int end) {
        if ((begin < 0) != (end < 0) || (begin >= 0 && end < begin)) {
            throw new IllegalStateException("Unbalanced vkdr completions markers in " + rcFile
                    + " - fix the file manually, then re-run.");
        }
    }

    private static List<String> readLines(Path file) throws IOException {
        return Files.exists(file)
                ? new ArrayList<>(Files.readAllLines(file, StandardCharsets.UTF_8))
                : new ArrayList<>();
    }

    private static int indexOfTrimmed(List<String> lines, String marker) {
        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).trim().equals(marker)) {
                return i;
            }
        }
        return -1;
    }

    /** One backup per rc file, so repeated upgrades don't litter $HOME. */
    private static void backup(Path rcFile) throws IOException {
        if (!Files.exists(rcFile)) {
            return;
        }
        Path bak = rcFile.resolveSibling(rcFile.getFileName() + ".vkdr-bak");
        if (!Files.exists(bak)) {
            Files.copy(rcFile, bak);
        }
    }

    /** Temp file in the same directory + atomic rename: an interrupted write cannot truncate. */
    private static void writeAtomically(Path target, String content) throws IOException {
        Path parent = target.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Path tmp = target.resolveSibling(target.getFileName() + ".vkdr-tmp");
        Files.writeString(tmp, content, StandardCharsets.UTF_8);
        try {
            Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (AtomicMoveNotSupportedException ex) {
            Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }
}
